const {chromium}=require('playwright');const fs=require('fs');
const user={id:'11111111-1111-4111-8111-111111111111',aud:'authenticated',role:'authenticated',email:'demo@example.test'};
const token=['eyJhbGciOiJIUzI1NiJ9',Buffer.from(JSON.stringify({sub:user.id,exp:Math.floor(Date.now()/1000)+36000,role:'authenticated'})).toString('base64url'),'demo'].join('.');
const session={access_token:token,refresh_token:'demo',expires_in:36000,expires_at:Math.floor(Date.now()/1000)+36000,token_type:'bearer',user};
const products=[{id:'oeufs',name:'Œufs Plein Air',ean13:'1234567890123',unit:'unité',brand:'Plein air',category:'pls',favorite:true,image_url:null,grammage_g:null,volume_ml:null,product_type:'oeuf'},{id:'patates',name:'Pommes de terre',ean13:'1234567890124',unit:'unité',brand:null,category:'fruits_legumes',favorite:true,image_url:null,grammage_g:1000,volume_ml:null,product_type:'pomme_de_terre'},{id:'oignons',name:'Oignons jaunes',ean13:'1234567890125',unit:'unité',brand:null,category:'fruits_legumes',favorite:true,image_url:null,grammage_g:500,volume_ml:null,product_type:'oignon'}];
const recipes=[{id:'rec1',name:'Poulet rôti aux légumes',servings_default:2,image_url:null,prep_minutes:15,cook_minutes:40,recipe_ingredients:[{id:'ing',name:'Pommes de terre',quantity_per_serving:300,unit:'g',rayon:'fruits_legumes',product_id:'patates'}]}];
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await b.newPage({viewport:{width:390,height:844},serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));let sent;
 await page.route('https://qmymwicsgilhoihtfdjm.supabase.co/**',async route=>{const req=route.request(),url=req.url();let data=[];if(url.includes('/auth/v1/user'))data=user;else if(url.includes('/auth/v1/token'))data=session;else if(url.includes('/rest/v1/products'))data=products;else if(url.includes('/rest/v1/recipes'))data=recipes;else if(url.includes('/rest/v1/cart_jobs')&&req.method()==='POST'){sent=req.postDataJSON();data={id:'job-demo'};}await route.fulfill({json:data});});
 await page.addInitScript(({session,id})=>{localStorage.setItem('sb-qmymwicsgilhoihtfdjm-auth-token',JSON.stringify(session));if(!localStorage.getItem('seeded-session')){localStorage.setItem('tablee-maison-v1:'+id,JSON.stringify({quotidien:{oeufs:'needed',patates:'needed'},quotidienQty:{oeufs:1,patates:2},manques:{'produit:oeufs':{name:'Œufs Plein Air',source:'widget'},'produit:patates':{name:'Pommes de terre',source:'widget'}}}));localStorage.setItem('seeded-session','yes');}}, {session,id:user.id});
 fs.mkdirSync('.impeccable/review/session-courses',{recursive:true});
 await page.goto('http://localhost:8082');await page.getByText('Les courses, à ton rythme.',{exact:true}).waitFor({timeout:60000});
 if(await page.getByText('À reprendre d’habitude',{exact:true}).count())throw Error('Old favourites section remains');
 await page.screenshot({path:'.impeccable/review/session-courses/home-phone.png'});
 await page.getByRole('button',{name:'Commencer une session',exact:true}).click();await page.getByRole('button',{name:'+ Choisir',exact:true}).click();
 await page.getByRole('button',{name:'Vérifier mes manques',exact:true}).click();await page.getByText('Vérifier mes manques',{exact:true}).last().waitFor();
 if(await page.getByRole('button',{name:'Continuer avec mes habitudes',exact:true}).isEnabled())throw Error('Unvalidated missing products can continue');
 await page.screenshot({path:'.impeccable/review/session-courses/missing-phone.png'});
 await page.getByRole('button',{name:'Confirmer 1 × Œufs Plein Air',exact:true}).click();await page.getByRole('button',{name:'Confirmer 2 × Pommes de terre',exact:true}).click();
 await page.getByRole('button',{name:'Faire une pause',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Reprendre ma session',exact:true}).click();
 await page.getByRole('button',{name:'Continuer avec mes habitudes',exact:true}).click();
 await page.getByRole('tab',{name:'Fruits & légumes'}).click();
 await page.getByRole('button',{name:'Il m’en faut 1 →',exact:true}).click();
 await page.getByRole('button',{name:'Continuer avec les achats exceptionnels',exact:true}).click();
 await page.getByRole('textbox',{name:'Produit manquant',exact:true}).fill('Pommes de terre bio');await page.getByRole('button',{name:'Noter Pommes de terre bio dans ma liste',exact:true}).click();
 await page.getByRole('button',{name:'Faire le bilan de ma liste',exact:true}).click();await page.getByText('Des doublons possibles',{exact:true}).waitFor();
 if(await page.getByRole('button',{name:'Choisir mon drive',exact:true}).isEnabled())throw Error('Duplicates can reach drive');
 await page.screenshot({path:'.impeccable/review/session-courses/recap-phone.png'});
 await page.getByRole('button',{name:'Retirer Pommes de terre bio',exact:true}).click();
 await page.setViewportSize({width:1024,height:1366});await page.screenshot({path:'.impeccable/review/session-courses/recap-tablet.png'});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow');
 await page.getByRole('button',{name:'Choisir mon drive',exact:true}).click();await page.getByRole('button',{name:'Envoyer à mon ordinateur',exact:true}).click();
 await page.waitForTimeout(600);if(!sent||sent.items.length!==3||sent.items.find(x=>x.product_id==='patates')?.quantity!==2)throw Error('Incorrect consolidated payload '+JSON.stringify(sent));
 if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({ok:true,items:sent.items,errors}));
 }catch(e){console.error(e);process.exitCode=1}finally{await b.close()}})();
