const {chromium}=require('playwright');const fs=require('fs');
const user={id:'11111111-1111-4111-8111-111111111111',aud:'authenticated',role:'authenticated',email:'demo@example.test'};
const token=['eyJhbGciOiJIUzI1NiJ9',Buffer.from(JSON.stringify({sub:user.id,exp:Math.floor(Date.now()/1000)+36000,role:'authenticated'})).toString('base64url'),'demo'].join('.');
const session={access_token:token,refresh_token:'demo',expires_in:36000,expires_at:Math.floor(Date.now()/1000)+36000,token_type:'bearer',user};
const products=[{id:'oeufs',name:'Œufs Plein Air',ean13:'1234567890123',unit:'unité',brand:'Plein air',category:'pls',favorite:true,image_url:null,grammage_g:null,volume_ml:null,product_type:'oeuf'},{id:'patates',name:'Pommes de terre',ean13:'1234567890124',unit:'unité',brand:null,category:'fruits_legumes',favorite:true,image_url:null,grammage_g:1000,volume_ml:null,product_type:'pomme_de_terre'},{id:'oignons',name:'Oignons jaunes',ean13:'1234567890125',unit:'unité',brand:null,category:'fruits_legumes',favorite:true,image_url:null,grammage_g:500,volume_ml:null,product_type:'oignon'}];
const recipes=[{id:'rec1',name:'Poulet rôti aux légumes',servings_default:2,image_url:null,prep_minutes:15,cook_minutes:40,recipe_ingredients:[{id:'ing',name:'Pommes de terre',quantity_per_serving:300,unit:'g',rayon:'fruits_legumes',product_id:'patates'}]}];
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const page=await b.newPage({viewport:{width:390,height:844},serviceWorkers:'block'});const errors=[];page.on('pageerror',e=>errors.push(e.message));let sent;let recipeBody,ingredientBody;
await page.route('https://qmymwicsgilhoihtfdjm.supabase.co/**',async route=>{const req=route.request(),url=req.url();let data=[];if(url.includes('/auth/v1/user'))data=user;else if(url.includes('/auth/v1/token'))data=session;else if(url.includes('/rest/v1/products'))data=products;else if(url.includes('/rest/v1/recipes')){if(req.method()==='POST'){recipeBody=req.postDataJSON();data={id:'created'};}else data=url.includes('id=eq.')?recipes[0]:recipes;}else if(url.includes('/rest/v1/recipe_ingredients')&&req.method()==='POST'){ingredientBody=req.postDataJSON();data=[];}else if(url.includes('/rest/v1/cart_jobs')&&req.method()==='POST'){sent=req.postDataJSON();data={id:'job-demo'};}await route.fulfill({json:data});});
await page.addInitScript(({session,id})=>{localStorage.setItem('sb-qmymwicsgilhoihtfdjm-auth-token',JSON.stringify(session));if(!localStorage.getItem('seeded')){localStorage.setItem('tablee-maison-v1:'+id,JSON.stringify({quotidien:{oeufs:'needed',patates:'needed'},quotidienQty:{oeufs:1,patates:1}}));localStorage.setItem('seeded','yes');}}, {session,id:user.id});
await page.goto('http://localhost:8082/recettes/rec1');
await page.getByRole('button',{name:'Plus de personnes',exact:true}).click();
await page.getByRole('button',{name:'Choisir ce repas',exact:true}).click();
await page.getByRole('button',{name:'Voir ma liste de courses',exact:true}).waitFor();
await page.getByText('900g',{exact:true}).waitFor();
await page.screenshot({path:'/tmp/recipe-detail-after.png'});
await page.setViewportSize({width:1100,height:900});await page.screenshot({path:'/tmp/recipe-detail-desktop.png'});
await page.setViewportSize({width:390,height:844});
await page.goto('http://localhost:8082/recettes/nouvelle');
await page.getByRole('button',{name:'Enregistrer ma recette',exact:true}).click();
await page.getByText('Donne un nom à ta recette.',{exact:true}).waitFor();
await page.getByLabel('Nom de la recette',{exact:true}).fill('Soupe maison');
await page.getByLabel('Préparation en minutes',{exact:true}).fill('15');
await page.getByRole('button',{name:'Ajouter un ingrédient',exact:true}).click();
await page.getByText('Pommes de terre',{exact:true}).click();
await page.getByLabel('Quantité totale de Pommes de terre',{exact:true}).fill('1,5');
await page.getByRole('button',{name:'Unité de Pommes de terre : unité',exact:true}).click();
await page.getByRole('button',{name:'kg',exact:true}).click();
await page.getByText('Choisir l’unité',{exact:true}).waitFor({state:'hidden'});
await page.screenshot({path:'/tmp/recipe-create-ingredients.png'});
await page.getByText('On note une bonne recette ?',{exact:true}).scrollIntoViewIfNeeded();
await page.screenshot({path:'/tmp/recipe-create-after.png'});
await page.setViewportSize({width:1100,height:900});await page.screenshot({path:'/tmp/recipe-create-desktop.png'});
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Enregistrer ma recette',exact:true}).click();
await page.getByText('Une recette de plus à partager.',{exact:true}).waitFor();
if(recipeBody.servings_default!==4||recipeBody.prep_minutes!==15||ingredientBody[0].quantity_per_serving!==.375||ingredientBody[0].unit!=='kg')throw Error('Conversion incorrecte '+JSON.stringify({recipeBody,ingredientBody}));
if(errors.length)throw Error(errors.join('\n'));
console.log(JSON.stringify({success:true,recipeBody,ingredientBody,overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)}));

}catch(e){console.error(e);process.exitCode=1}finally{await b.close()}})();
