import { useState, useEffect, type ReactNode } from 'react';
import { Image, Pressable, Text, View, StyleSheet, type ImageStyle, type StyleProp } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { colors } from '../lib/theme';
import { photoSecours } from '../lib/photos-maison';
export function Photo({name,url,style,recipe=false}:{name:string;url?:string|null;style?:StyleProp<ImageStyle>;recipe?:boolean}) {
  const [failed,setFailed] = useState(false);
  useEffect(()=>setFailed(false),[url,name]);
  const fallback=photoSecours(name),source=!failed&&url?.trim()?{uri:url}:fallback;
  return source?<Image source={source} accessibilityLabel={name} style={[ui.photo,style]} resizeMode={recipe?'cover':'contain'} onError={()=>setFailed(true)}/>:<View style={[ui.photo,style as any,ui.placeholder]}><Feather name={recipe?'image':'package'} size={25} color={colors.textMuted}/></View>;
}
export function Action({children,onPress,secondary=false,disabled=false}:{children:ReactNode;onPress:()=>void;secondary?:boolean;disabled?:boolean}) {return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[ui.button,secondary&&ui.secondary,disabled&&{opacity:.5}]}><Text style={[ui.buttonText,secondary&&{color:colors.accent}]}>{children}</Text></Pressable>}
export function Head({title,back=false}:{title:string;back?:boolean}) {return <View style={ui.header}>{back&&<Pressable accessibilityRole="button" accessibilityLabel="Revenir aux courses" onPress={()=>router.replace('/')} style={ui.iconButton}><Feather name="chevron-left" size={24} color={colors.text}/></Pressable>}<Text style={[ui.title,{flex:1}]}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="Réglages" onPress={()=>router.push('/compte')} style={ui.avatar}><Feather name="user" size={21} color="white"/></Pressable></View>}
export function ScanAction(){return <Pressable accessibilityRole="button" onPress={()=>router.push('/scan')} style={ui.scan}><Feather name="maximize" size={20} color={colors.accent}/><Text style={ui.link}>Scanner un produit</Text></Pressable>}
export const ui=StyleSheet.create({
 screen:{flex:1,backgroundColor:colors.bg},content:{padding:20,paddingBottom:28,gap:12},header:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:12},title:{fontSize:27,fontWeight:'700',color:colors.text,letterSpacing:-.6},heading:{fontSize:29,lineHeight:33,fontWeight:'700',color:colors.text,letterSpacing:-.6},subtitle:{fontSize:15,lineHeight:22,color:colors.textMuted},section:{fontSize:20,fontWeight:'600',color:colors.text,marginTop:14},avatar:{width:44,height:44,borderRadius:22,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},iconButton:{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'},button:{minHeight:48,borderRadius:12,backgroundColor:colors.accent,padding:14,alignItems:'center',justifyContent:'center'},secondary:{backgroundColor:colors.accentSoft},buttonText:{fontSize:15,fontWeight:'600',color:'white'},scan:{minHeight:48,borderRadius:12,backgroundColor:colors.accentSoft,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},link:{fontSize:14,color:colors.accent,fontWeight:'600'},row:{flexDirection:'row',alignItems:'center',gap:10},sectionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},product:{backgroundColor:'white',borderRadius:12,padding:10,flexDirection:'row',alignItems:'center',gap:10},photo:{width:60,height:64,borderRadius:8},placeholder:{alignItems:'center',justifyContent:'center',backgroundColor:colors.accentSoft},productName:{fontSize:15,fontWeight:'600',color:colors.text},detail:{fontSize:13,lineHeight:19,color:colors.textMuted,marginTop:3},add:{width:44,height:44,borderRadius:22,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},input:{borderWidth:1,borderColor:colors.border,borderRadius:12,minHeight:48,padding:12,backgroundColor:'white',color:colors.text,fontSize:16},notice:{backgroundColor:colors.accentSoft,padding:14,borderRadius:12},error:{color:colors.danger,fontSize:14,lineHeight:20},footer:{padding:16,gap:8,backgroundColor:'white',borderTopWidth:1,borderTopColor:colors.border},counter:{flexDirection:'row',alignItems:'center',backgroundColor:colors.bg,borderRadius:10},num:{minWidth:25,textAlign:'center',fontSize:16,color:colors.text,fontVariant:['tabular-nums']}
});
