const photos: Record<string, number> = {
  'pommes de terre': require('../assets/tablee/products/pommes-de-terre.webp'),
  'oignons jaunes': require('../assets/tablee/products/oignons.webp'),
  'œufs plein air': require('../assets/tablee/products/oeufs.webp'),
  "recharge gaz universelle": require('../assets/tablee/products/gaz.webp'),
  "sacs réutilisables consignés drive": require('../assets/tablee/products/sac.webp'),
  "essuie-tout ultra absorption blanc carrefour": require('../assets/tablee/products/essuie-tout.webp'),
  "briquet maxi colorés": require('../assets/tablee/products/briquet.webp'),
  "pommes de terre de conservation vrac": require('../assets/tablee/products/pommes-de-terre.webp'),
  "oignons jaunes vrac": require('../assets/tablee/products/oignons.webp'),
  "papier toilette confort doux": require('../assets/tablee/products/papier-toilette.webp'),
  "savon liquide mains lait et miel carrefour": require('../assets/tablee/products/savon.webp'),
  "dentifrice anti-tartre": require('../assets/tablee/products/dentifrice.webp'),
  "brosse à dents classique medium médium carrefour": require('../assets/tablee/products/brosse-dents.webp'),
  "déodorant bille anti-transpirant protection 5 sans alcool": require('../assets/tablee/products/deodorant.webp'),
  "gel douche hypoallergénique peaux normales": require('../assets/tablee/products/gel-douche.webp'),
  "mouchoirs confort 3 epaisseurs ultra doux fsc carrefour": require('../assets/tablee/products/mouchoirs.webp'),
  "papier toilette doux et épais triple épaisseur décoré essential carrefour": require('../assets/tablee/products/papier-toilette.webp'),
  "poulet rôti aux légumes": require('../assets/tablee/recipes/poulet-roti.webp'),
  "gratin dauphinois": require('../assets/tablee/recipes/gratin-dauphinois.webp'),
  "salade césar": require('../assets/tablee/recipes/salade-cesar.webp'),
  "pâtes à la carbonara": require('../assets/tablee/recipes/carbonara.webp'),
  "crêpes sucrées": require('../assets/tablee/recipes/crepes.webp'),
};
export const photoSecours = (name: string) => photos[name.trim().toLowerCase()];
